EXPERIMENT:
  ID: YourID # Give your logs and model a unique name

##Data
DATA:
  TRANSFORM: True # If true, the points are pose-aligned before feeding to the model
  POSES: "poses.txt" # Name of the pose file provided in each sequence folder
  SHUFFLE: True
  NUM_WORKER: 4
  DELTA_T_DATA: 0.1 # Time between scans in the dataset (0.1s for KITTI)
  VOXEL_SIZE: 0.1 # Used for discretization in x,y,z when creating a sparse tensor 
  SEMANTIC_CONFIG_FILE: "./config/semantic-kitti-mos.yaml" 
  SPLIT:
    TRAIN:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 9
      - 10
    VAL:
      - 8
    TEST:
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
 
##Training
TRAIN:
  N_GPUS: 1
  MAX_EPOCH: 60
  LR: 0.0001
  LR_EPOCH: 1
  LR_DECAY: 0.99
  WEIGHT_DECAY: 0.0001
  BATCH_SIZE: 2
  ACC_BATCHES: 1
  AUGMENTATION: True

##Network
MODEL:
  DELTA_T_PREDICTION: 0.1 # Temporal resolution of scans
  N_PAST_STEPS: 10
